# WARNING: Storing passwords directly in this file is INSECURE
# as it commits them to Git. Use Render Secret Files or Environment Groups instead.

# Render Blueprint Specification: https://render.com/docs/blueprint-spec

# --- Try defining disks at the top level ---
disks:
  - name: blog-db-data # Define the disk name here
    sizeGB: 1         # Define size here
    # mountPath is defined where it's used (in the service)

services:
  #---------------------------------------
  # MySQL Database (Private Service)
  #---------------------------------------
  - type: pserv # Private Service
    name: blog-db
    image:
      url: mysql:8.0
    region: oregon # IMPORTANT: Choose YOUR region
    plan: free
    # --- Reference the disk and specify mountPath here ---
    disk: # Use singular 'disk' to reference the defined disk
      name: blog-db-data # Reference the disk defined above
      mountPath: /var/lib/mysql # Specify where to mount it in this service
    envVars:
      - key: MYSQL_DATABASE
        value: blogappbd
      - key: MYSQL_ROOT_PASSWORD
        value: "root" # <-- Using root as password

  #---------------------------------------
  # Spring Boot Application (Web Service)
  #---------------------------------------
  - type: web # Web Service
    name: blog-app
    env: docker
    region: oregon # IMPORTANT: Use the SAME region
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${blog-db.internalHost}:3306/blogappbd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: "root" # <-- Using root as password
      - key: PORT
        value: 8080