# WARNING: Storing passwords directly in this file is INSECURE.

# Render Blueprint Specification: https://render.com/docs/blueprint-spec
services:
  #---------------------------------------
  # MySQL Database (Private Service)
  #---------------------------------------
  - type: pserv # Private Service
    name: blog-db
    # --- ADDED: Explicitly state it's Docker ---
    env: docker
    image:
      url: mysql:8.0
    region: oregon # IMPORTANT: Choose YOUR region
    # --- CHANGED: Free plan doesn't support disks for pserv ---
    plan: starter # Or another paid plan that supports disks
    # Persistent Disk configuration
    envVars:
      - key: MYSQL_DATABASE
        value: blogappbd
      - key: MYSQL_ROOT_PASSWORD
        value: "root" # <-- INSECURE: Replace if not using 'root'

  #---------------------------------------
  # Spring Boot Application (Web Service)
  #---------------------------------------
  - type: web # Web Service
    name: blog-app
    env: docker # Correctly specified as Docker
    region: oregon # IMPORTANT: Use the SAME region
    # --- Web Service can often stay on free if resources suffice ---
    plan: free # Or choose a paid instance type if needed
    # Build settings
    dockerContext: .
    dockerfilePath: ./Dockerfile
    # Environment variables
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${blog-db.internalHost}:3306/blogappbd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: "root" # <-- INSECURE: Use the same password as MYSQL_ROOT_PASSWORD
      - key: PORT
        value: 8080